apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP    #Cluster IP is the default type
  ports:
  - targetPort: 80  #the port which the backend is exposed
    port: 80        
  selector:        
    app: myapp
    type: back-end
